---
apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: "{{ k8s_init_token }}"
apiServerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
  runtime-config: "storage.k8s.io/v1alpha1=true"
controllerManagerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
schedulerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
