---
# https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: "{{ k8s_version }}"
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    token: "{{ k8s_init_token }}"
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
apiServerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
  runtime-config: "storage.k8s.io/v1alpha1=true"
controllerManagerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
schedulerExtraArgs:
  feature-gates: "{{ feature_gates|join(',') }}"
