---
sudo: false
matrix:
  include:
    # markdownlint: https://github.com/markdownlint/markdownlint
    # https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
    - name: markdownlinter
      language: ruby
      install:
        - gem install asciidoctor mdl
      script:
        - >
          find . -regextype egrep -iregex '.*\.adoc' -print0 |
            xargs -0rt -n1 asciidoctor -o /dev/null -v --failure-level WARN
        - >
          find . -regextype egrep -iregex '.*\.md' -print0 |
            xargs -0rt mdl

    # shellcheck
    - name: shellcheck
      language: bash
      script:
        - >
          find . -regextype egrep -iregex '.*\.(ba)?sh' -print0 |
            xargs -0rt shellcheck

    # yamllint
    - name: yamllint
      language: python
      install:
        - pip install yamllint
      script:
        - >
          find . -regextype egrep -iregex '.*\.ya?ml' -print0 |
            xargs -0rt yamllint
