---
- hosts: all
  become: true
  tasks:
    - name: Disable selinux
      selinux:
        policy: targeted
        state: permissive
    - name: Add k8s repo
      template:
        src: ../templates/k8s.repo.j2
        dest: /etc/yum.repos.d/k8s.repo
    - name: Add k8s prereq packages
      yum:
      #dnf:
        state: present
        name: "{{ item }}"
      with_items:
        - docker
        - iproute
        #- iproute-tc
        - kubeadm
        - kubectl
        - kubelet
    - name: Enable kubelet
      systemd:
        service: kubelet
        state: started
        enabled: true
    - name: Enable docker
      systemd:
        service: docker
        state: started
        enabled: true
    - name: Enable net bridge iptables
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
        reload: yes
    - name: Enable net bridge ip6tables
      sysctl:
        name: net.bridge.bridge-nf-call-ip6tables
        value: 1
        state: present
        reload: yes
