---

- name: Create LVM partition
  parted:
    device: /dev/{{ item }}
    label: msdos
    part_type: primary
    number: 1
    part_start: 1MiB
    flags: [ lvm ]
    state: present
  with_items: "{{ gluster_disks }}"

- name: Create LVM VG
  lvg:
    pvs: /dev/{{ item }}1
    vg: vg_brick
  with_items: "{{ gluster_disks }}"

- name: Create VG thin pool
  command: lvcreate -l 100%FREE --thinpool vg_brick/pool
  args:
    creates: /dev/mapper/vg_brick-pool

- include: mk_brick.yml brick_name='b1' brick_size='5G'
